---
- name: Set timezone variables
  copy:
    content: Etc/UTC
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - update timezone

- name: Add ntpd.conf
  lineinfile:
    dest: /etc/openntpd/ntpd.conf
    regexp: "{{ item }}"
    line: "{{ ntp_settings[item] }}"
    state: present
  notify: restart ntpd
  with_items:
    - "{{ ntp_settings | list }}"

- name: Start ntpd
  service:
    name: openntpd
    state: started
    enabled: yes
