---
- name: Ensure sshd_config settings
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^{{ item }}"
    line: "{{ item }} {{ sshd_settings[item] }}"
    state: present
  notify: restart ssh
  with_items:
    - "{{ sshd_settings | list }}"

- name: Start ssh
  service:
    name: ssh
    state: started
    enabled: yes
