---
- name: Ensure sshguard service is started and enabled on boot
  service:
    name: "{{ sshguard_service }}"
    state: "{{ sshguard_service_state }}"
    enabled: "{{ sshguard_service_enabled }}"
  when: not molecule | default(false)

- name: Configure sshguard and whitelist from templates
  template:
    src: "sshguard/{{ item }}.j2"
    dest: "{{ sshguard_config_path }}/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ sshguard_config_items }}"
  notify: restart sshguard
