---
- name: Add deploy user
  user:
    name: "{{ deploy_user }}"
    password: "{{ lookup('password', '/tmp/mysqlpassword length=15') | password_hash('sha512') }}"
    uid: "{{ deploy_user_uid }}"
    shell: "{{ deploy_user_shell }}"
    home: "{{ deploy_user_home }}"
    update_password: on_create


- name: Add authorized keys for deploy user
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', item) }}"
  with_items:
    - "{{ deploy_user_public_keys }}"
  when: deploy_user_public_keys is defined


- name: Add deploy user to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ deploy_user }} ALL"
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present
