---
- name: Create user
  user:
    name: "{{ std_user }}"
    password: "{{ lookup('password', '/tmp/user_password length=15') | password_hash('sha512') }}"
    uid: "{{ std_user_uid }}"
    shell: "{{ std_user_shell }}"
    home: "{{ std_user_home_dir }}"
    update_password: on_create

- name: Add authorized keys for user
  authorized_key:
    user: "{{ std_user }}"
    key: "{{ lookup('file', item) }}"
  with_items:
    - "{{ std_user_public_keys }}"

- name: Add user to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ std_user }} ALL"
    line: "{{ std_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present
