---
- name: restart ntpd
  service:
    name: "openntpd"
    state: restarted

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart sshguard
  service:
    name: "{{ sshguard_service }}"
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted
