FROM ubuntu:20.04

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN apt-get update && apt-get install -y python sudo bash ca-certificates iproute2 && apt-get clean;
