---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: instance
    image: ubuntu:20.04
    dockerfile: molecule/default/Dockerfile.j2
    pre_build_image: false
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          deploy_user_public_keys: molecule/default/junk_key
verifier:
  name: ansible
