---
- name: Include tests for user tasks
  include_tasks: user.yml

- name: Include tests for apt tasks
  include_tasks: apt.yml

- name: Ensure sshguard is installed
  service:
    name: sshguard
    state: started
    enabled: yes

- name: Ensure ssh is installed
  service:
    name: ssh
    state: started
    enabled: yes

- name: Ensure opennttpd is installed
  service:
    name: openntpd
    state: started
    enabled: yes
